apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpaq-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpaq-dep
  template:
    metadata:
      labels:
        app: cpaq-dep
    spec:
      os:
        name: windows
      nodeSelector:
        kubernetes.io/os: windows
        kubernetes.azure.com/os-sku: Windows2022
      containers:
        - name: cpaq
          image: cordicdev.azurecr.io/cpaq
          ports:
            - { name: mgw, containerPort: 41152 }
            - { name: https, containerPort: 443 }
            - { name: http, containerPort: 80 }
          volumeMounts:
          env:
            - name: CORDIC_PATH
              value: "C:\\Cordic"
            - name: CORDIC_LOCALE
              value: "en-GB"
            - name: CORDIC_FLEET_DISPLAY
              value: "Cabbage Ltd"
            - name: CORDIC_FLEET_NAME
              value: "Cabbage"
            - name: CORDIC_SITE
              value: "9999900007"
            - name: CORDIC_SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: sqlServer
            - name: CORDIC_SQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: sqlDatabase
            - name: CORDIC_SQL_USER
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: sqlUser
            - name: CORDIC_SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: sqlPassword
---
apiVersion: v1
kind: Service
metadata:
  name: cpaq-svc-mgw
spec:
  ports:
    - port: 41152
      name: mgw
      targetPort: 41152
  selector:
    app: cpaq-dep
---
apiVersion: v1
kind: Service
metadata:
  name: cpaq-svc-iis
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
  selector:
    app: cpaq-dep
