apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  tls:
    - hosts:
        - db-test.aks.rk3.dev
  rules:
    - host: "db-test.aks.rk3.dev"
