apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-1

resources:
  - ../../../shared/store-app

patches:
  - path: deployment-example-1.yaml
  - path: ingress-example-1.yaml
