apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{Namespace}}

resources:
  - ../../../shared/portal
  - ./namespace.yaml
  - ./secrets.yaml

patches:
  - path: ingress-patch.json
    target:
      name: cpaq-portal-ing
      kind: Ingress

images:
  - name: cordicdev.azurecr.io/cpaq-portal
    newTag: {{PortalVersion}}
